name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.10'
          cache: 'pnpm'
          cache-dependency-path: |
            'pnpm-lock.yaml'
            'functions/pnpm-lock.yaml'

      - name: Install pnpm
        run: npm install -g pnpm@~10.12

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@~14.11

      - name: Install Frontend dependencies
        run: pnpm install

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_THINGS_TO_COMPLETE }}

      - name: Build Frontend
        run: pnpm run build

      - name: Deploy Frontend to Firebase Hosting
        run: |
          firebase deploy -f --only hosting --project things-to-complete

      - name: Install Functions dependencies
        run: pnpm install
        working-directory: ./functions

      - name: Deploy functions
        run: |
          firebase deploy -f --only functions --project things-to-complete
